### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by z1haze** [brianmcdo/votifier#1]
Hey, can you explain what this actually does? Is this something that would be used from a vote site to send votes to a server? I'm just about finished build a vote site and I dont yet have anything sending the votes out yet.

**Comment by brianmcdo** [comment]
This is basically an application that acts as a votifier compatible server allowing you to receive votes from a voting site and process them using an anonymous function.

**Comment by z1haze** [comment]
Oh, I need to send the votes off so this won't work. Why would someone want to receive them on a website when they are only used in a game

**Comment by brianmcdo** [comment]
I run a vanilla server so keeping track of votes would be impossible without it.

**Comment by z1haze** [comment]
Good point
